Convert blocks
PrefectHQ/prefect-azure pull request #39
Opened 2022-07-25 06:29 UTC by ahuang11

## Summary

Convert credentials into blocks

## Relevant Issue(s)

2022-07-25 16:13 UTC, desertaxle requested changes

2022-07-25 16:13 UTC, desertaxle commented on prefect_azure/credentials.py
> +
"Azure Blob Storage Credentials" reads a little more naturally, I think. Might make sense to update the class name too?
```suggestion
    _block_type_name = "Azure Blob Storage Credentials"
    _logo_url = "https://images.ctfassets.net/gm98wzqotmnx/6AiQ6HRIft8TspZH7AfyZg/39fd82bdbb186db85560f688746c8cdd/azure.png?h=250"  # noqa
```

2022-07-25 16:13 UTC, desertaxle commented on prefect_azure/credentials.py
> +    _logo_url = "https://github.com/PrefectHQ/orion/blob/main/docs/img/collections/azure.png?raw=true"  # noqa
Starting with Azure makes sure that they'll all be next to each other in the blocks UI. Maybe update the class name too?
```suggestion
    _block_type_name = "Azure Cosmos DB Credentials"
    _logo_url = "https://images.ctfassets.net/gm98wzqotmnx/6AiQ6HRIft8TspZH7AfyZg/39fd82bdbb186db85560f688746c8cdd/azure.png?h=250"  # noqa
```

2022-07-25 16:13 UTC, desertaxle commented on prefect_azure/credentials.py
>                      "service_principal_password",
`service_principal_password = "service_principal_password"`

2022-07-25 16:13 UTC, desertaxle commented on prefect_azure/credentials.py
> +    _logo_url = "https://github.com/PrefectHQ/orion/blob/main/docs/img/collections/azure.png?raw=true"  # noqa
```suggestion
    _block_type_name = "AzureML Credentials"
    _logo_url = "https://images.ctfassets.net/gm98wzqotmnx/6AiQ6HRIft8TspZH7AfyZg/39fd82bdbb186db85560f688746c8cdd/azure.png?h=250"  # noqa
```

2022-07-25 16:13 UTC, desertaxle commented on prefect_azure/credentials.py
> +class MlAzureCredentials(Block):
Update to match block type name?
```suggestion
class AzureMlCredentials(Block):
```

2022-07-25 16:18 UTC, ahuang11 commented
If we change class name, does this mean the next version should be 1.0.0 since it's technically breaking?

2022-07-25 16:22 UTC, desertaxle commented
We're below 1.0.0 right now, which normally implies that the API isn't stable yet. We can bump to 0.2.0 and note breaking changes in the change log.

2022-07-26 17:43 UTC, desertaxle approved these changes

2022-07-26 17:44 UTC, merged